SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE session;
TRUNCATE TABLE shipment;
TRUNCATE TABLE order_item;
TRUNCATE TABLE product;
TRUNCATE TABLE _order;
TRUNCATE TABLE client;
TRUNCATE TABLE manager;
SET FOREIGN_KEY_CHECKS=1;
